sqoop import \
	--connect 'jdbc:as400://cmmp.corn.cargill.com:449;libraries=division;prompt=false' \
	--driver com.ibm.as400.access.AS400JDBCDriver \
	--username ps900191 \
	--password SSN@cmmp18 \
	--target-dir hdfs://nameservice1/dev/internal/cmmp/clean/sqoop_prctc \
	--as-textfile \
	--hive-import \
	--create-hive-table \
	--hive-partition-key 'CDCITY' \
	--hive-table dev_internal_cmmp.sqoop_prctc \
	--split-by 'CDLOC' \
	--fields-terminated-by ',' \
	--lines-terminated-by '\n' \
	--m 4 \
	--query 'select CDLOC,CDTYPE,CDDESC from FDTB09PIBP where $CONDITIONS'
